MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.Contract.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        //DI
        private readonly IMovieService _movieService;
        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        [HttpGet]
        //show details of the movie
        public async Task<IActionResult> Details(int idWen)
        {
            var movie =await _movieService.GetMovieDetails(idWen);

            return View(movie);
        }




        [HttpGet]
        public async Task<IActionResult> Genre(int id, int pageSize=30, int pageNumber=1)
        {
            //each time only fetch 30 movies of the picked genre
            var pagedMovies = await _movieService.GetMoviesByGenre(id, pageSize, pageNumber);
            return View("PagedMovies",pagedMovies);
        }
    }
}

MovieShopMVC/Controllers/UserController.cs
using ApplicationCore.Contract.Services;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Controllers
{
    [Authorize]   //apply on the whole class. look into the httpContext find cookie, decrypt claim and pop into User obj, these method gonna use.
    //If not login successfully, there will be no cookie(claims), no needed inform to excute these methods.
    public class UserController : Controller
    {
        //DI get login User infor from cookie, claim principle
        private readonly ICurrentLogedInUser _currentLogedInUser;
        private readonly IUserService _userService;
            public UserController(ICurrentLogedInUser currentLogedInUser, IUserService userService)
        {
            _currentLogedInUser = currentLogedInUser;
            _userService = userService;
        }


        //all these action methods should only be excuted when user is loged in.
        [HttpGet]
        //before excute the login user's methods. need a code to authorize
        // Authorize Filter is built in , also can write costomed filter.
        public async Task<IActionResult> Purchase()
        {

            //go to database and get all the movies purchased by user, by user id in the http request cookies
            //var cookie = this.HttpContext.Request.Cookies["MovieShopAuthCookie"];
            var userId = _currentLogedInUser.UserId;
            var purchasedMovie= await _userService.GetAllPurchasesForUser(userId);

            return View(purchasedMovie);
        }

      

        [HttpGet]
        public async Task<IActionResult> Favorite()
        {
            //same as Purchase
            var userId = _currentLogedInUser.UserId;
            var favorMovie = await _userService.GetAllFavoritesForUser(userId);

            return View(favorMovie);
        }

        [HttpGet]
        public async Task<IActionResult> AddFavorite(int movieId)
        {
            //if (!_currentLogedInUser.IsAuthenticated)
            //{
            //    return RedirectToAction("Login");
            //}

            var favoriteConfirm = await _userService.AddFavorite(movieId, _currentLogedInUser.UserId);
            
           
            return LocalRedirect($"~/Movies/Details?idWen={movieId}"); //return page need twice, then can back to homepage
        }

        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddReview(ReviewModel reviewModel)
        {
            var userId = _currentLogedInUser.UserId;
            reviewModel.UserId = userId;
            var addConfirm = await _userService.AddMovieReview(reviewModel);
            return View();//new HttpStatusCodeResult(200); //new EmptyResult();  return Ok status, empty page
        }
       

        [HttpGet]  //Important get or post!!
        public async Task<IActionResult> BuyMovie(int movieId)
        {
            //if (!_currentLogedInUser.IsAuthenticated)
            //{
            //    return RedirectToAction("Login");
            //}

            var purchaseConfirm= await _userService.PurchaseMovie(movieId, _currentLogedInUser.UserId);
            //return LocalRedirect("~/");

            if (purchaseConfirm)
            {
                return View();
            }
            return RedirectToAction("Details"); //wrong???

        }

    }


}

MovieShopMVC/Views/Shared/Components/Genres/GenresViewComponent.cs
using ApplicationCore.Contract.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Views.Shared.Components.Genres
{
    public class GenresViewComponent:ViewComponent
    {
        //DI
        private readonly IGenreService _genreService;
        public GenresViewComponent(IGenreService genreService)
        {
            _genreService = genreService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.GetAllGenres();
            return View(genres);
        }

    }
}

MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieShopMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*-----------------------add drop down genre menu-------------------------------*@
                         <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="dropdownMenuButton1" data-bs-toggle="dropdown">Genres</a>
                            <div class="dropdown-menu">
                                @*call the Genre view component *@
                                @await Component.InvokeAsync("Genres")
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    @*--------------login and register-------------- *@
                    <partial name="_LoginInfo"></partial>
                    @*---------------------------*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()  
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShopMVC/Views/Shared/_LoginInfo.cshtml
@using MovieShopMVC.Services

@*In view, DI can just use keyword inject, indicate in program.cs*@
@inject ICurrentLogedInUser currentUser

@*hide login and reigister button if user is authenticated and show user Fullname, email and links for profile and logout*@
@if (currentUser.IsAuthenticated)
{
	<div class="text-end dropdown me=3">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
   Hi, @currentUser.FullName
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" asp-controller="User" asp-action="Purchase" >Purchases</a></li>
    <li><a class="dropdown-item" asp-controller="User" asp-action="Favorite">Favorites</a></li>
    <li><a class="dropdown-item" asp-controller="User" asp-action="Profile">View Profile/Account</a></li>
    <li><a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a></li>
  </ul>
</div>
}
else
{
    @*show show and register buttons if user is not login*@
    @*UseExtensions this partial view in layout *@
    <div class="text-end">
        <a class="btn btn-outline-promary me-3" asp-controller="Account" asp-action="Login">Login</a>
         <a class="btn btn-outline-promary me-3" asp-controller="Account" asp-action="Register">Register</a>
    </div>
}

MovieShopMVC/Views/Shared/_MovieCard.cshtml
@*Movie Card Partial view will be reused across multiple views in our application*@

@*//lower-case model, tell view what data type Model-passing-parameter is expecting*@
@model ApplicationCore.Models.MovieCardModel 



<div class="card mb-4 shadow">
                <a asp-controller="Movies" asp-action="Details" asp-route-idWen="@Model.Id" target="_self">
                   @*route to https://localhost:5500/movies/details/2*@
                   @*asp-route-(name is the same as action method input parameter name)*@
                    <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Id" />
                </a>
               
</div>