MovieShopMVC/Controllers/CastController.cs
using ApplicationCore.Contract.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class CastController : Controller
    {
        private ICastService _castService;
        public CastController(ICastService castService)
        {
            _castService = castService;
        }
        public async Task<IActionResult> CastDetails(int idCast)
        {
            var castDetails=await  _castService.GetCastDetails(idCast);
            return View(castDetails);
        }
    }
}

MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.Contract.Services;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        //DI
        private readonly IMovieService _movieService;
        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        [HttpGet]
        //show details of the movie
        public async Task<IActionResult> Details(int idWen)
        {
            var movie =await _movieService.GetMovieDetails(idWen);

            return View(movie);
        }




        [HttpGet]
        public async Task<IActionResult> Genre(int id, int pageSize=30, int pageNumber=1)
        {
            //each time only fetch 30 movies of the picked genre
            var pagedMovies = await _movieService.GetMoviesByGenre(id, pageSize, pageNumber);
            return View("PagedMovies",pagedMovies);
        }
    }
}

MovieShopMVC/Controllers/UserController.cs
using ApplicationCore.Contract.Services;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Services;

namespace MovieShopMVC.Controllers
{
    [Authorize]   //apply on the whole class. look into the httpContext find cookie, decrypt claim and pop into User obj, these method gonna use.
    //If not login successfully, there will be no cookie(claims), no needed inform to excute these methods.
    public class UserController : Controller
    {
        //DI get login User infor from cookie, claim principle
        private readonly ICurrentLogedInUser _currentLogedInUser;
        private readonly IUserService _userService;
            public UserController(ICurrentLogedInUser currentLogedInUser, IUserService userService)
        {
            _currentLogedInUser = currentLogedInUser;
            _userService = userService;
        }


        //all these action methods should only be excuted when user is loged in.
        [HttpGet]
        //before excute the login user's methods. need a code to authorize
        // Authorize Filter is built in , also can write costomed filter.
        public async Task<IActionResult> Purchase()
        {

            //go to database and get all the movies purchased by user, by user id in the http request cookies
            //var cookie = this.HttpContext.Request.Cookies["MovieShopAuthCookie"];
            var userId = _currentLogedInUser.UserId;
            var purchasedMovie= await _userService.GetAllPurchasesForUser(userId);

            return View(purchasedMovie);
        }

      

        [HttpGet]
        public async Task<IActionResult> Favorite()
        {
            //same as Purchase
            var userId = _currentLogedInUser.UserId;
            var favorMovie = await _userService.GetAllFavoritesForUser(userId);

            return View(favorMovie);
        }

        [HttpGet]
        public async Task<IActionResult> AddFavorite(int movieId)
        {
            //if (!_currentLogedInUser.IsAuthenticated)
            //{
            //    return RedirectToAction("Login");
            //}

            var favoriteConfirm = await _userService.AddFavorite(movieId, _currentLogedInUser.UserId);
            
           
            return LocalRedirect($"~/Movies/Details?idWen={movieId}"); //return page need twice, then can back to homepage
        }

        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddReview(ReviewModel reviewModel)
        {
            var userId = _currentLogedInUser.UserId;
            reviewModel.UserId = userId;
            var addConfirm = await _userService.AddMovieReview(reviewModel);
            return View();//new HttpStatusCodeResult(200); //new EmptyResult();  return Ok status, empty page
        }
       

        [HttpGet]  //Important get or post!!
        public async Task<IActionResult> BuyMovie(int movieId)
        {
            //if (!_currentLogedInUser.IsAuthenticated)
            //{
            //    return RedirectToAction("Login");
            //}

            var purchaseConfirm= await _userService.PurchaseMovie(movieId, _currentLogedInUser.UserId);
            //return LocalRedirect("~/");

            if (purchaseConfirm)
            {
                return View();
            }
            return RedirectToAction("Details"); //wrong???

        }

    }


}

MovieShopMVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetialsModel


<section>
	<div class="row" style="background-image: url('http://mediacloud.theweek.com/image/private/s--gdgBalU9--/v1608654335/screen_shot_2020-08-24_at_1.15.08_pm.png');">
        <div class="col - 4">
		<img src="@Model.PosterUrl" class="img-fluid w-50" alt="@Model.Title" style="margin-left:5em;"/>
        </div>

		<div class="col-5">
		    <h3 class="text-white">@Model.Title</h3>
			<p class="text-white">@Model.RunTime min | @Model.ReleaseDate
					@foreach (var genre in Model.Genres)
					{
						<span class="rounded bg-secondary text-white">@genre.Name</span>
					}
			</p>
			@*include Review Table, one movie => multiple reviews, calculate average rating in MovieService*@

			<span class="rounded bg-success text-white text-right">@Model.Ave_rating</span>
			<p class="text-white">@Model.Overview</p>
        </div>


		<div class="col-3">
			@*This will fire another page*@
            @*<a asp-controller="User" asp-action="Review" target="_blank">
				<div><button type="button" class="btn btn-outline-secondary text-white float-right" style="margin-top:2em; margin-left:4em; width:10em;">&rarrhk; Review</button></div>
			</a>
			<a asp-controller="User" asp-action="OrderConfirm" target="_blank">
				<div><button type="button" class="btn btn-white bg-white text-dark float-right" style="margin-top:2em; margin-left:4em; width:10em;">Buy $9.90</button></div>
			</a>*@
			@*using Bootstrap Button Trigger Modal*@

		@*----------------popup button Modal for Review----------------------------*@
<button type="button" class="btn  btn-outline-secondary text-white" data-bs-toggle="modal" data-bs-target="#ReviewModal" style="margin-top:2em; margin-left:4em; width:10em;">&rarrhk; Review</button>
<!-- Modal -->
<div class="modal fade" id="ReviewModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">&raquo; Review Input</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
	  @*-------------------*@
         <form asp-action="AddReview" asp-controller="User">
			 <div class="form-group">
				<span>Review for : @Model.Title  </span>
            </div>

  <div class="form-group">
    <label for="Rating">Rating</label>
    <select class="form-control" name="Rating" id="Rating">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
      <option>6</option>
      <option>7</option>
      <option>8</option>
      <option>9</option>
      <option>10</option>
    </select>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Review</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="ReviewText"></textarea>
  </div>

        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary"  name="MovieId" value="@Model.Id">Save</button>
        </div>

        </form>
      </div>
    </div>
  </div>
</div>

@*-------------------popup button Modal for buy----------------------------*@
<button type="button" class="btn  btn-white bg-white text-dark" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin-top:2em; margin-left:4em; width:10em;">Buy $9.90</button>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">&raquo; Retail Information</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
	  @*---------------*@
	  <p>The Price of <b>@Model.Title</b> is:</p>
	  <p><b>$ @Model.Price</b></p>
      @*----------------*@
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a class="btn btn-primary" asp-action="BuyMovie" asp-controller="User" asp-route-movieId="@Model.Id">Confirm</a>
      </div>
    </div>
  </div>
</div>
       @*----------------add likes-----------------*@
	 @using MovieShopMVC.Services
	 @using ApplicationCore.Contract.Services;
     @inject ICurrentLogedInUser currentUser
	 @inject IUserService userService
	
	 @{bool favorCheck=false;}
	 @if (@currentUser.IsAuthenticated)
		{
			favorCheck = await userService.FavoriteExists(Model.Id, currentUser.UserId);
		}
	

	@if(@currentUser.IsAuthenticated && favorCheck)
	{
		<div class="text-white text-center fs-2" style="margin-top:0.6em">&hearts;</div>
    }
	  else
	  {<div class="text-center" style="margin-top:2em">
           <a class="btn btn-outline-secondary text-white" asp-action="AddFavorite" asp-controller="User" asp-route-movieId="@Model.Id"> Likes </a>
       </div>
	  }

      

        </div>
    </div>
    @*---------------------------section for movie fact & trailers---------------------------------*@
	<div class="row" style="margin-top:2em;">
        <div class="col-4">

		<h5>MOVIE FACTS</h5>
		<hr>
		<ul class="list-group list-group-flush">
           
			   <li class="list-group-item">
				   &ccupssm; Release Date<span class="bg-secondary text-white" style="margin-left:1em; border-radius:8px">@Model.ReleaseDate</span>
			   </li>
			    <li class="list-group-item">
				   &rAtail; Run Time<span class="bg-secondary text-white" style="margin-left:1em; border-radius:8px">@Model.RunTime m</span>
			   </li>
			    <li class="list-group-item">
				   &boxbox; Box Office<span class="bg-secondary text-white" style="margin-left:1em;border-radius:8px ">$ @Model.Revenue</span>
			   </li>
			    <li class="list-group-item">
				   &dollar; Budget<span class="bg-secondary text-white" style="margin-left:1em; border-radius:8px">$ @Model.Budget</span>
			   </li>
        </ul>


		<h5 style="margin-top:2em;">TRAILERS</h5>
		<hr>
		<ul class="list-group list-group-flush">
           @foreach (var trailer in Model.Trailers)
		   {
			   <li class="list-group-item">
				   <a href="@trailer.TrailerUrl" target="_blank"> <img style="width:2em;" src="https://e7.pngegg.com/pngimages/437/213/png-clipart-youtube-play-button-computer-icons-now-button-angle-logo.png"> </a>
				   <span style="margin-left:1em; font-size:0.7em">@trailer.Name</span>
			   </li>
		   }
        </ul>
		
        </div>

		<div class="col-8">
		<h5>CAST</h5>
		<hr>
		
		<ul class="list-group list-group-flush">
           @foreach (var cast in Model.Casts)
		   {
			   <a asp-controller="Cast" asp-action="CastDetails" asp-route-idCast="@cast.Id" target="_self">
				    <li class="list-group-item">
				       <img src="@cast.ProfilePath" class="rounded-circle" style="width:1.5em; position:relative;">
				       <span style="margin-left:3em;">@cast.Name</span>
				       <span style="position:absolute; left:22em;" >@cast.Character</span>
			        </li>
			   </a>
			  
		   }
        </ul>


        </div>

    </div>


</section>

MovieShopMVC/Views/Movies/PagedMovies.cshtml
@model ApplicationCore.Models.PagedResultSetModel<ApplicationCore.Models.MovieCardModel>

<div class="rounded">
    <div class="container bg-light">
        <div class="row">
            @foreach (var movie in Model.PagedData)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">

                    <partial name="_MovieCard" model="movie" />
                </div>

            }
        </div>
    </div>
</div>

@*Display previous and Next Buttons-----------------------
  When you are on first Page Previous button should be disabled
  When you are on last page Next button should be disabled *@

@*
@{
    var previousDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a class="btn btn-primary @previousDisabled" asp-action="Genre" asp-controller="Movies" asp-route-pageNumber="@(Model.PageNumber-1)">
    Previous
</a>
<a class="btn btn-primary @nextDisabled" asp-action="Genre" asp-controller="Movies" asp-route-pageNumber="@(Model.PageNumber + 1)">
    Next
</a>
*@

@*---------------or-----------------*@
@*Display all the page numbers 1000 records 1000/30 => 34 pages 1 2 3 ......34*
When you are on first Page then disable First Page, when on last page disable last 34 page button
*@

@{
    var PreDisabled = ((@Model.PageNumber-1)<1) ? "disabled" : "";
    var curDisabled = ((Model.PageNumber)>@Model.TotalPages)? "disabled" : "";
    var oneDisabled = ((Model.PageNumber)>@Model.TotalPages)? "disabled" : "";
    var twoDisabled = ((Model.PageNumber+1)>@Model.TotalPages)? "disabled" : "";
    var threeDisabled = ((Model.PageNumber+2)>@Model.TotalPages)? "disabled" : "";
    var nextDisabled = ((Model.PageNumber+3)>@Model.TotalPages)? "disabled" : "";
}

<nav aria-label="...">
  <ul class="pagination">
    <li class="page-item @PreDisabled">
      <a class="page-link" asp-action="Genre" asp-controller="Movies" asp-route-pageNumber="@(Model.PageNumber-1)">Previous</a>
    </li>
    <li class="page-item @curDisabled"><a class="page-link" asp-action="Genre" asp-controller="Movies" asp-route-pageNumber="@Model.PageNumber">@Model.PageNumber</a></li>
    <li class="page-item @oneDisabled"><a class="page-link" asp-action="Genre" asp-controller="Movies" asp-route-pageNumber="@(Model.PageNumber+1)">@(Model.PageNumber+1)</a></li>
    <li class="page-item @twoDisabled"><a class="page-link" asp-action="Genre" asp-controller="Movies" asp-route-pageNumber="@(Model.PageNumber+2)">@(Model.PageNumber+2)</a></li>
    <li class="page-item @threeDisabled"><a class="page-link" asp-action="Genre" asp-controller="Movies" asp-route-pageNumber="@(Model.PageNumber+3)">...</a></li>
    <li class="page-item @nextDisabled">
      <a class="page-link" asp-action="Genre" asp-controller="Movies" asp-route-pageNumber="@(Model.PageNumber+4)">Next</a>
    </li>
  </ul>
</nav>